---
version: "3"
services:

  LB:
    image: nginx:alpine
    container_name: LB
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./cert/:/etc/ssl/
    networks:
      - api-cache
    
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - api-cache

  ipstack1:
    image: fujikomalan/ipstack:v1
    container_name: ipstack1
    restart: always
    environment:
      - CACHING_SERVER=172.31.45.75
      - IPSTACK_KEY=e895****************************  ### ==> Your ipstack API KEY
    networks:
      - api-cache

  ipstack2:
    image: fujikomalan/ipstack:v1
    container_name: ipstack2
    restart: always
    environment:
      - CACHING_SERVER=172.31.45.75
      - IPSTACK_KEY=e895****************************  ### ==> Your ipstack API KEY
    networks:
      - api-cache

  ipstack3:
    image: fujikomalan/ipstack:v1
    container_name: ipstack3
    restart: always
    environment:
      - CACHING_SERVER=172.31.45.75
      - IPSTACK_KEY=e895****************************  ### ==> Your ipstack API KEY
    networks:
      - api-cache


networks:
  api-cache: 

